version: '3'
services:

 mysql:
  build: ./mysql
#  image: tassanai/serviceswarm_mysql:V1
  ports:
   - "3306:3306"
  deploy:
   mode: replicated
   replicas: 1
   restart_policy:
    condition: on-failure

 express:
  build: ./express_session
#  image: tassanai/serviceswarm_express:V1
  ports:
   - "3001:3000"
  links:
   - mysql
  environment:
   - REDIS_SERVER=172.16.1.76
   - REDIS_PORT=6379
   - IP_LOCAL_HOST=172.16.1.76
   - MACHINE_NAME=NODE_LOCAL
  deploy:
   mode: replicated
   replicas: 1
   resources:
    limits:
      cpus: "0.1"
      memory: 50M
   restart_policy:
    condition: on-failure

 nginx:
  build: ./nginx
#  image: tassanai/serviceswarm_nginx:V1
  volumes:
   - ./nginx/nginx_conf/local/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - express
  ports:
   - "8081:80"
  environment:
   - NGINX_HOST=172.16.1.76
   - PROXY_PASS=http://172.16.1.76:3001
  deploy:
   mode: replicated
   replicas: 1
   restart_policy:
    condition: on-failure