version: '3'
services:

 mysql:
#  build: ./mysql
  image: tassanai/serviceswarm_mysql:V1
  ports:
   - "3306:3306"
  deploy:
   mode: replicated
   replicas: 2
   restart_policy:
    condition: on-failure

 express:
#  build: ./express_session
  image: tassanai/serviceswarm_express:V1
  ports:
   - "3000:3000"
  links:
   - mysql
  environment:
   - REDIS_SERVER=192.168.56.1
   - REDIS_PORT=6379
  deploy:
   mode: replicated
   replicas: 2
   resources:
    limits:
      cpus: "0.1"
      memory: 50M
   restart_policy:
    condition: on-failure

 nginx:
#  build: ./nginx
  image: tassanai/serviceswarm_nginx:V1
  links:
   - express
  ports:
   - "8080:80"
  deploy:
   mode: replicated
   replicas: 2
   restart_policy:
    condition: on-failure