version: '3'
services:

 mysql:
  image: tassanai/serviceswarm_mysql:V1
  ports:
   - "3306:3306"
  deploy:
   mode: replicated
   replicas: 2
   restart_policy:
    condition: on-failure

 express:
  image: tassanai/serviceswarm_express:V1
  ports:
   - "3000:3000"
  links:
   - mysql
  environment:
   - REDIS_SERVER=192.168.56.1
   - REDIS_PORT=6379
  deploy:
   mode: replicated
   replicas: 2
   resources:
    limits:
      cpus: "0.1"
      memory: 50M
   restart_policy:
    condition: on-failure

 nginx:
  image: tassanai/serviceswarm_nginx:V1
  volumes:
    - ./nginx/nginx_conf/master1/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - express
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=172.20.10.69;
   - PROXY_PASS=http://172.20.10.69:3000;
  deploy:
   mode: replicated
   replicas: 2
   restart_policy:
    condition: on-failure