version: '3'
services:

 mysql:
  build: ./mysql
  ports:
   - "3306:3306"

 express:
  build: ./express_session
  ports:
   - "3000:3000"
  links:
   - mysql
  environment:
   - REDIS_SERVER=192.168.56.1
   - REDIS_PORT=6379

 nginx:
  build: ./nginx
  links:
   - express
  ports:
   - "8080:80"